bsenv/brainstation/urls.py
from django.contrib import admin
from django.urls import path
from meal import views
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name="index"),
    url(r'',include("meal.urls")),
]

bsenv/meal/urls.py
from meal import views
from django.conf.urls import url

app_name = 'meal'

urlpatterns = [
    url(r'^menu/', views.menu, name="menu"),
    url(r'^tokens/', views.token_list, name="token_list"),
    url(r'^registration/', views.registration, name="registration"),
    url(r'^user/', views.user, name="user"),
    url(r'^profile/', views.profile_list, name="profile_list"),
    url(r'^view/', views.view_detail, name='view_detail'),
]

bsenv/meal/models.py
from django.db import models
from django.utils import timezone
from decimal import Decimal


class Token(models.Model):
    empName = models.CharField(max_length=200)
    empId = models.DecimalField( max_digits=19, decimal_places=0)
    phone = models.DecimalField(max_digits=13, decimal_places=0)
    lunch = models.CharField(max_length=20)
    meal_date = models.DateField(auto_now=True)


class User(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    email = models.EmailField(max_length=70, blank=True)
    phone = models.DecimalField(max_digits=13, decimal_places=0)
    password = models.CharField(max_length=50)


class Data(models.Model):
    firstName = models.CharField(max_length=200, null=True)
    lastName = models.CharField(max_length=200, null=True)

bsenv/meal/forms.py
from django import forms
from .models import Token
from .models import User


class TokenForm(forms.ModelForm):
    class Meta:
        model = Token
        fields = [
            'empName',
            'empId',
            'phone',
            'lunch',
            ]


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'firstName',
            'lastName',
            'email',
            'phone',
            'password',
            ]

bsenv/meal/views.py
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse
from .models import Token
from .models import User
from .models import Data
from .forms import TokenForm
from .forms import UserForm
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
def index(request):
    return render(request, "index.html")


def menu(request):
    return render(request, "menu.html")


def token_list(request):
    tokens = Token.objects.all()
    return render(request, "token_list.html", {'tokens': tokens})


def registration(request):
    form = TokenForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return index(request)
        else:
            form = TokenForm()
    return render(request, 'registration.html', {'form': form})


def user(request):
    form = UserForm
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print("error! check model,view & form file.")
    return render(request, 'user.html', {'form': form})


def profile_list(request):
    profiles = User.objects.all()
    return render(request, "profile.html", {'profiles': profiles})

@csrf_exempt
def view_detail(request):
    if request.method == "POST":
        if request.POST.get('firstName') and request.POST.get('lastName'):
            name = Data()
            #print(request.POST.get('data'))
            name.firstName = request.POST.get('firstName')
            name.lastName = request.POST.get('lastName')
            name.save()
            return render(request, "data.html")
    else:
        return render(request, "data.html")

bsenv/templates/data.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Data </title>
</head>
<body>
    <div>
        <input id="fName"  type="text" class="query-search" placeholder="First Name">
        <input id="lName"  type="text" class="query-search" placeholder="Last Name">
        <input onclick="setGetParameter()" type="button" class="btn btn-primary" value = "save"/>
    </div>


<script>
    function setGetParameter(){
        var fName = $("#fName").val();
        var lName = $("#lName").val();
        $.ajax({
          type: "POST",
          url: 'http://127.0.0.1:8000/view/',
          data:{firstName:fName,
            lastName:lName
          },

          success: function(result){
            alert("Success");
          },
          error:function(err){
            alert(err)
          }
        });
    }
</script>
</body>
</html>

bsenv/templates/index.html
<!doctype html>
<html lang="en" xmlns:meal="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Brain Staion Mealing System</title>
</head>
<body>
<h4>Shah Imran</h4>
<a href="{% url "meal:menu"%}">next page.</a><br>
<br>
<a href="{% url "meal:token_list"%}">tokens.</a><br>
<br>
<a href="{% url "meal:registration" %}"> registration here</a><br>
<br>
<p><a href="{% url "meal:user"%}">User Registration</a></p><br>

<p><a href="{% url "meal:profile_list"%}">Show profiles</a></p>
<p><a href="{% url "meal:view_detail"%}">input data</a></p>


</body>
</html>

bsenv/templates/menu.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Meal Menu</title>
</head>
<body>
<h4>Menu list</h4>
<ul>
    <li>Rice</li>
    <li>Ruti</li>
    <li>None</li>
</ul>
</body>
</html>

bsenv/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>profile</title>
</head>
<body>
    <div>
        <table>
            <th>First Name</th>
            <th>last Name</th>
            <th>Email</th>
            <th>Phone</th>
            {% for profile in profiles %}
                <tr>
                    <td>{{ profile.firstName }}</td>
                    <td>{{ profile.lastName }}</td>
                    <td>{{profile.email}}</td>
                    <td>{{profile.phone}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
</body>
</html>

bsenv/templates/registration.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Lunch page</title>
</head>
<body>
    <div >
        {% block content %}
            <h1>New Data</h1>
                <form method="POST" >
                    {% csrf_token %}
                    <label for="empName">Employee Name:</label>
                    <input type="text" name="empName"><br>
                    <label for="empId">Empolyee Id:</label>
                    <input type="number" name="empId"><br>
                    <label for="phone">Phone No.:</label>
                    <input type="number" name="phone"><br>
                    <label for="lunch">Choose launch:</label>
                    <select name="lunch" id="">
                        <option value="Rice" selected>Rice</option>
                        <option value="Ruti">Ruti</option>
                        <option value="None">None</option>
                    </select>
                    <br>
                    <button type="submit" >Submit</button>
                </form>
        {% endblock %}
    </div>
</body>
</html>

bsenv/templates/signUp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>
<body>
    <div>

    </div>
</body>
</html>

bsenv/templates/token_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>Token list</title>
</head>
<body>
<div class="col-lg-2"></div>
    <div class="col-lg-8">
        <table>
            {% for token in tokens %}
                <tr>
                    <td>Employee Name:{{ token.empName }}</td>
                    <br>
                    <td>Employee ID:{{ token.empId }}</td>
                    <br>
                    <td>Phone Number:{{ token.phone }}</td>
                    <br>
                    <td>Lunch Type:{{ token.lunch }}</td>
                    <td>Date:{{ token.meal_date }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
<div class="col-lg-2"></div>
</body>
</html>

bsenv/templates/user.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>User registation</title>
</head>

<body>

        {% block content %}
        <div class="col-lg-3"></div>
            <div class="col-lg-6" id="ui">
                <h1 class="text-center border border-light p-5">User Registration</h1>
                    <form method="POST" class="text-center border border-light p-5">
                        <div class="form-group" >
                            {% csrf_token %}
                            <div class="row">
                                <div>
                                <div class="col-lg-6">
                                    <label >First Name:</label>
                                    <input type="text" name="firstName" class="form-control">
                                </div>
                                <div class="col-lg-6">
                                    <label >Last Name:</label>
                                    <input type="text" name="lastName" class="form-control">
                                </div>
                            </div>

                            <label for="email">Email:</label>
                            <input type="email" name="email" class="form-control"><br>
                            <label for="phone">Phone:</label>
                            <input type="number" name="phone" class="form-control"><br>
                            <label for="password">Password:</label>
                            <input type="password" name="password" class="form-control"><br>
                            <button type="submit" class="btn btn-info my-4 btn-block">Submit</button>
                        </div>
                            </div>


                    </form>
             </div>
        <div class="col-lg-3"></div>
        {% endblock %}


</body>
</html>